// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/client/connect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/client/connect.post').default>>>>
    }
    '/api/client/disconnect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/client/disconnect.post').default>>>>
    }
    '/api/clients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clients.get').default>>>>
    }
    '/api/history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/history.get').default>>>>
    }
    '/api/message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/message.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}