// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/1/18 19:36:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/peach0x33a/source/repos/node/type-cloud/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/plugins/**/*.{js,ts,mjs}","/home/peach0x33a/source/repos/node/type-cloud/composables/**/*.{js,ts,mjs}","/home/peach0x33a/source/repos/node/type-cloud/utils/**/*.{js,ts,mjs}","/home/peach0x33a/source/repos/node/type-cloud/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/peach0x33a/source/repos/node/type-cloud/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;